#!/bin/sh

set -e

apk --no-cache add apache2 wget curl tar vim nano zip sqlite \
	postgresql16-client mysql-client

# Move whole /var/www to /usr/www
mv /var/www /usr/www

# Listen on 8080, enable mpm_event
sed -i \
	-e "/^ServerRoot/s, .*, /usr/www," \
	-e "/^DocumentRoot/,/^<\/Directory>/d" \
	-e "/^Listen/s/.*/Listen 8080/" \
	-e "/^LoadModule mpm_/s/^/#/" \
	-e "/^#LoadModule mpm_event_module/s/^#//" \
	/etc/apache2/httpd.conf

# test if original mpm configuration exists, then overwrite it
test -f /etc/apache2/conf.d/mpm.conf
mv /etc/apache2/conf.d/zz-mpm.conf /etc/apache2/conf.d/mpm.conf

# Redirect logs to stdout/stderr
chmod 755 /var/log/apache2
ln -s /dev/stdout /var/log/apache2/access.log
ln -s /dev/stderr /var/log/apache2/error.log

# Run smoketest
httpd -t -T

rm "$0"
