#!/bin/sh

set -e

if [ -z "$1" ]; then
	echo "Specify php version as first arg"
	exit 1
fi

php="php${1}"

exclude="(pecl|cgi|dbg|dev|doc|fpm|phalcon|phpdbg)"

packages=$(apk --no-cache search ${php}- | grep "^${php}-" | grep -vE "${php}-${exclude}-" | sed -r -e "s/-[^-]+-[^-]+$//")

apk --no-cache add tzdata ${packages}

# Enable mpm_prefork
sed -i \
	-e "/^Listen/s/.*/Listen 8080/" \
	-e "/^LoadModule mpm_/s/^/#/" \
	-e "/^#LoadModule mpm_prefork_module/s/^#//" \
	/etc/apache2/httpd.conf

# tune php upload max size
sed -i \
	-e "/^upload_max_filesize /s/=.*/= 20M/" \
	-e "/^post_max_size /s/=.*/= 32M/" \
	/etc/${php}/php.ini

# Run smoketest
httpd -t -T

rm "$0"
